name: Build Android APK

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Specify the distribution
          java-version: '17'
          java-package: jdk

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel
          pip3 install kivy cython

      - name: Install Buildozer
        run: |
          pip3 install buildozer

      - name: Install Android SDK
        run: |
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          mkdir -p $HOME/.android/cmdline-tools/latest
          unzip commandlinetools-linux-7302050_latest.zip -d $HOME/.android/cmdline-tools/latest
          yes | $HOME/.android/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/.android/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          cd src  # Change to your project directory
          buildozer -v android debug  # Use 'release' for a release build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: src/bin/*.apk  # Adjust the path to your APK
