name: Build Android APK

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use the appropriate Java version for your project

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel
          pip3 install kivy

      - name: Install Buildozer
        run: |
          pip3 install buildozer

      - name: Build APK
        run: |
          cd your_project_directory  # Change to your project directory
          buildozer -v android debug  # Use 'release' for a release build

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: Anmol-Lipi-Python-apk/bin/*.apk  # Adjust the path to your APK
